Add replace and search solutions
s-pyadyshev/ru-study-ruby pull request #1
Opened 2022-12-08 18:28 UTC by s-pyadyshev

2022-12-12 07:02 UTC, greybutton requested changes

2022-12-28 11:31 UTC, s-pyadyshev commented on test/exercise/arrays/solution.rb
> +        $maxNum = 0;
1-2 исправил

2022-12-28 11:31 UTC, s-pyadyshev commented on test/exercise/arrays/solution.rb
> +        array.each_with_index do |num, i|
исправил

2022-12-28 11:31 UTC, s-pyadyshev commented on test/exercise/arrays/solution.rb
>        def search(_array, _query)
переделал на рекурсию

2022-12-29 06:30 UTC, greybutton approved these changes

2022-12-29 07:59 UTC, merged